spring:
  profiles:
    active: dev-eureka
server:
  port: ${PORT:7071}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
---
spring:
  profiles: dev-eureka
eureka:
  instance:
    hostname: dev-eureka
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.71.174.22}:${EUREKA_SERVER_PORT:7071}/eureka/
---
spring:
  profiles: stage-eureka1
eureka:
  instance:
    hostname: stage-eureka1
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.71.174.22}:${EUREKA_SERVER_PORT:7071}/eureka/
---
spring:
  profiles: stage-eureka2
eureka:
  instance:
    hostname: stage-eureka1
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://10.71.172.22}:${EUREKA_SERVER_PORT:7071}/eureka/