---
server:
  port: 7071
spring:
  profiles:
    active: eureka1
eureka:
  instance:
    hostname: eureka-service1
  client:
    service-url:
      defaultZone: http://10.71.174.22:7071/eureka/
    registerWithEureka: true
    fetchRegistry: false
  server:
    enable-self-preservation: true
---
spring:
  profiles: eureka2
server:
  port: 7071
eureka:
  instance:
    hostname: eureka-service2
  client:
    service-url:
      defaultZone: http://10.71.172.22:7071/eureka/
    registerWithEureka: true
    fetchRegistry: false
  server:
    enable-self-preservation: true
